### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by jgn46**
I think I already added this files to the original. Sorry lol. I didn't know what I was doing.

### CODE REVIEW

**Comment by ryanwithani** [comment]
What is the templates/header.php file? I don't think anyone has written it and it says its required for the threads.php file to function. @jgn46

**Comment by jgn46** [comment]
The header.php file is the nav bar

**Comment by jgn46** [comment]
Its not finished through. I was just trying out the pull request stuff

**Comment by ryanwithani** [comment]
Okay, well since you were just practicing I'm going to close this. :)

**Pull request closed without merging**
